server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# server 설정안하면 default는 8080 포트, path : / 이다.
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/   # prefix : 컨트롤러가 리턴을 할 때 앞에 붙여주는 경로명.
      suffix: .jsp              # suffix : 컨트롤러가 리턴을 할 때 뒤에 붙여주는 경로명.
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: kdj
    password: kdj0630
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false